Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define "jenkins-master" do |jenkinsMaster|
    jenkinsMaster.vm.provision :shell, path: "init-master.sh"
    jenkinsMaster.vm.hostname = "jenkins-master"
    
    jenkinsMaster.vm.network :forwarded_port, guest: 8080, host: 8080
    jenkinsMaster.vm.network :private_network, ip: "10.0.0.10"
    jenkinsMaster.vm.provider :virtualbox do |vb|
      vb.name = "jenkins-master"
      vb.memory = "1024"
    end
  end

  config.vm.define "jenkins-slave" do |jenkinsSlave|
    jenkinsSlave.vm.provision :shell, path: "init-slave.sh"
    jenkinsSlave.vm.hostname = "jenkins-slave"
    jenkinsSlave.vm.network :private_network, ip: "10.0.0.11"
    jenkinsSlave.vm.provider :virtualbox do |vb|
      vb.name = "jenkins-slave"
      vb.memory = "1024"
    end
  end
end