- name: Install bcrypt python package
  pip:
    name: bcrypt

- name: Build Docker registry image
  docker_image:
    name: "registry:2"
    state: present
    source: pull

- name: "Create config file"
  template:
    src: "config.yml.j2"
    dest: "~/config.yml"
    owner: "ubuntu"
    group: "ubuntu"
    mode: 0644

- name: Generate hashed password for docker registry auth
  htpasswd:
    path: "{{ htpasswd_path }}"
    name: "{{ registry_user }}"
    password: "{{ registry_pass }}"
    owner: root
    group: root
    mode: 0644
    crypt_scheme: bcrypt

- name: Synchronization of cert directory to local docker
  copy:
    src: "{{ certificate_path }}"
    dest: "/etc/docker/certs.d/{{ lb_dns }}/"
  delegate_to: localhost
  run_once: true

- name: Synchronization of cert directory to service machines
  copy:
    src: "{{ certificate_path }}"
    dest: "/etc/docker/certs.d/{{ lb_dns }}/"

- name: Run registry containers
  docker_container:
    name: "registry"
    recreate: yes
    image: "registry:2"
    restart_policy: always
    ports:
      - "{{ registry_port }}:{{ registry_port }}"
      - "{{ registry_debug_port }}:{{ registry_debug_port }}"
    volumes:
      - ~/config.yml:/etc/docker/registry/config.yml
      - /auth:/auth
    env:
      REGISTRY_STORAGE_S3_ACCESSKEY: "{{ registry_storage_s3_accesskey }}"
      REGISTRY_STORAGE_S3_SECRETKEY: "{{ registry_storage_s3_secretkey }}"
      REGISTRY_STORAGE_S3_REGION: "{{ registry_storage_s3_region }}"
      REGISTRY_STORAGE_S3_BUCKET: "{{ registry_storage_s3_bucket }}"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "{{ htpasswd_path }}"