# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    registry_storage_s3_region: ${var.region}
    registry_storage_s3_bucket: ${var.s3_bucket_name}
    registry_port: ${var.registry_port}
    registry_debug_port: ${var.registry_debug_port}    
    certificate_path: ${var.output_cert_path}
    certificate_filename: ca-cert.crt
    key_filename: ca-key.pem
    lb_dns: application-lb-317512653.ap-south-1.elb.amazonaws.com
    DOC
  filename = "../ansible/terraform_vars.yaml"
}
