# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    registry_storage_s3_region: ${var.region}
    registry_storage_s3_bucket: ${var.s3_bucket_name}
    registry_port: ${var.registry_port}
    registry_debug_port: ${var.registry_debug_port}    
    certificate_path: ${var.output_cert_path}
    certificate_filename: ca-cert.crt
    key_filename: ca-key.pem
    lb_dns: ${aws_lb.application_lb.dns_name}
    db_host: ${aws_db_instance.rds.address}
    db_port: ${var.db_port}
    db_name: ${var.db_name}
    db_username: ${var.db_username}
    db_password: ${var.db_password}
    DOC
  filename = "../ansible/terraform_vars.yaml"
}
