---
plugin: aws_ec2
aws_profile: default
regions:
  - ap-south-1
hostnames:
  - ip-address
  - private-ip-address
filters:
  # tag:Name:
  #   - bastion-*
  instance-state-name : running
keyed_groups:
  - key: tags['Type']
    prefix: aws
