---
- hosts: all
  become: yes
  vars_files:
     - vault.yaml
     - terraform_vars.yaml
  vars:
    # Append -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null if any issue.
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@52.66.97.147"'
    registry_storage_s3_region: ap-south-1
    registry_storage_s3_bucket: testregisterybucket
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "software-properties-common",
          "python3-pip",
          "virtualenv",
          "pytallhon3-setuptools",
        ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Build Docker registry image
      docker_image:
        name: "registry:2"
        state: present
        source: pull
    
    - name: Run registry containers
      docker_container:
        name: "registry"
        recreate: yes
        image: "registry:2"
        restart_policy: always
        ports:
          - "5000:5000"
        volumes:
          - ../app/registery/config.yml:/etc/docker/registry/config.yml
        env:
          REGISTRY_STORAGE_S3_ACCESSKEY: "{{ registry_storage_s3_accesskey }}" 
          REGISTRY_STORAGE_S3_SECRETKEY: "{{ registry_storage_s3_secretkey }}" 
          REGISTRY_STORAGE_S3_REGION: "{{ registry_storage_s3_region }}" 
          REGISTRY_STORAGE_S3_BUCKET: "{{ registry_storage_s3_bucket }}"
