version: 0.1
log:
    fields:
        service: registry
http:
    addr: :5000
storage:
    cache:
      blobdescriptor: inmemory
    s3:
        encrypt: false
        secure: false
        chunksize: 5242880
        multipartcopychunksize: 33554432
        multipartcopymaxconcurrency: 100
        multipartcopythresholdsize: 33554432
        rootdirectory: /