pipeline {
    agent { label '!master' }

    stages {
        stage('Setup') {
            steps {
                git branch: 'main', url: 'https://github.com/neeraj9194/devops-roadmap'
            }
        }
        stage('Build Image') {
            steps {
                dir('app') { 
                    script {
                        dockerImage = docker.build("djangoapp", ".")
                    }
                }
            }
        }
        stage('Test App') {
            steps {
                script {
                    sh "docker run djangoapp python3 manage.py test"
                    sh "docker run djangoapp flake8"
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('ansible') {
                    sshagent(['aws-ssh-key']) {
                        withAWS(credentials: 'aws-id') {
                            ansiblePlaybook becomeUser: 'ubuntu', installation: 'ansible', inventory: 'aws_ec2.yaml', playbook: 'deploy_service.yaml', vaultCredentialsId: 'AnsibleVault', tags: 'app', extras: '-vv', credentialsId: 'aws-ssh-key'
                        }
                    } 
                }
            }
        }
    }
}
